services:
  - type: web
    name: enginimate-backend
    runtime: python
    plan: free
    autoDeploy: true
    buildCommand: uv sync --frozen --no-install-project && uv cache prune --ci && uv pip install .
    startCommand: uvicorn backend.routes.main:app --host 0.0.0.0 --port $PORT
